- name: Provision Web Servers on AWS
  hosts: aws
  become: yes

  tasks:
    - name: Enable nginx1 repo (Amazon Linux 2)
      command: amazon-linux-extras enable nginx1
      args:
        creates: /etc/yum.repos.d/nginx.repo
      when: ansible_facts['distribution'] == "Amazon"

    - name: Clean yum metadata
      command: yum clean metadata
      when: ansible_facts['distribution'] == "Amazon"

    - name: Install web server
      package:
        name: "{{ webserver }}"
        state: present
      notify: restart nginx

    - name: Ensure firewalld is installed
      package:
        name: firewalld
        state: present

    - name: Ensure firewalld is running
      service:
        name: firewalld
        state: started
        enabled: true

    - name: Open required ports in firewalld
      firewalld:
        port: "{{ item }}/tcp"
        state: enabled
        permanent: true
        immediate: true
      loop: "{{ ports }}"

    - name: Check if www.companyplus.com directory exists
      stat:
        path: /var/www/html/www.companyplus.com
      register: companyplus_dir

    - name: Report directory status
      block:
        - name: Directory exists
          debug:
            msg: "/var/www/html/www.companyplus.com exists"
      when: companyplus_dir.stat.exists

    - name: Report missing directory
      debug:
        msg: "/var/www/html/www.companyplus.com is missing"
      when: not companyplus_dir.stat.exists

  roles:
  - role: webserver
    vars:
      app_root: html_demo_site-main
      server_name: "{{ ansible_facts['default_ipv4']['address'] }}"
      document_root: /var/www/html

